#!/bin/sh

name=$(run car "$1")
value=$(run eval "$(run car "$(run cdr "$1")")")

echo "FROM docker-lisp/base-bash" > "$SCOPE_PATH/$name"
echo "ENV CMD='echo \"$value\"'" >> "$SCOPE_PATH/$name"

echo "$value"
