#!/bin/sh
set -e

if [ -z "$1" ]; then
  echo "Usage: ./scripts/build <file> [image-name]"
  echo "Build a dockerfile into docker-lisp/<image-name>"
  echo "If image-name is omitted, uses the filename"
  exit 1
fi

file="$1"
name="${2:-$(basename "$file")}"

docker build --platform=linux/amd64 --provenance=false -q -t "docker-lisp/$name" -f "$file" . > /dev/null
