#!/bin/bash
set -e

cd "$(dirname "$0")/.."

build_base() {
  name="$1"
  echo "Building docker-lisp/$name..."
  ./scripts/build "bases/$name"
}

build_base base-call
build_base base-bash
build_base base-chicken
